'use strict';
const fs = require('node:fs');
const path = require('node:path');
const XLSX = require('../assets/js/vendor/xlsx.full.min.js');
const SG = require('../assets/js/core/sheet-grid.js');

const src = path.join(__dirname, '..', 'data', 'source', 'crossfit-phase-1.xlsx');
const out = path.join(__dirname, '..', 'tests', 'fixtures', 'phase1-grid.js');

const wb = XLSX.read(fs.readFileSync(src), { type: 'buffer' });
const name = wb.SheetNames[0];
const grid = SG.fromWorksheet(XLSX, wb.Sheets[name]);

// Trim trailing all-empty rows; the sheet declares 891 rows but uses ~53.
let last = grid.length - 1;
while (last >= 0 && grid[last].every((c) => c.v === '' && c.link === null)) last--;
const trimmed = grid.slice(0, last + 1);

fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(
  out,
  '// Generated by tools/build-fixture.js from data/source/crossfit-phase-1.xlsx\n' +
  "// Do not edit by hand. Regenerate with: \"$NODE\" tools/build-fixture.js\n" +
  "'use strict';\n" +
  'module.exports = ' + JSON.stringify({ name: name, grid: trimmed }, null, 1) + ';\n',
  'utf8'
);
console.log('wrote', out, trimmed.length, 'rows');
