'use strict';
const fs = require('node:fs');
const path = require('node:path');
const XLSX = require('../assets/js/vendor/xlsx.full.min.js');
const SG = require('../assets/js/core/sheet-grid.js');
const P = require('../assets/js/core/parse-grid.js');

const src = path.join(__dirname, '..', 'data', 'source', 'crossfit-phase-1.xlsx');
const out = path.join(__dirname, '..', 'data', 'seed-program.js');

const wb = XLSX.read(fs.readFileSync(src), { type: 'buffer' });
const sheetName = wb.SheetNames[0];
const grid = SG.fromWorksheet(XLSX, wb.Sheets[sheetName]);

const program = P.gridToProgram(grid, {
  id: 'seed-crossfit-phase-1',
  name: sheetName.trim(),
  source: 'crossfit-phase-1.xlsx',
  importedAt: '2026-08-24T00:00:00.000Z'
});

if (!program) throw new Error('parser returned null for the seed workbook');

const body =
  '// Generated by tools/build-seed.js from data/source/crossfit-phase-1.xlsx\n' +
  '// Do not edit by hand.\n' +
  "'use strict';\n" +
  '(function (root) {\n' +
  '  var seed = ' + JSON.stringify(program, null, 1) + ';\n' +
  '  root.PTT = root.PTT || {};\n' +
  '  root.PTT.seed = seed;\n' +
  "  if (typeof module !== 'undefined' && module.exports) module.exports = seed;\n" +
  '})(typeof globalThis !== \'undefined\' ? globalThis : this);\n';

fs.writeFileSync(out, body, 'utf8');
console.log('wrote', out, program.days.length, 'days', program.exerciseCount, 'exercises');
